### ISSUE TITLE
Z-index issue

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/angular-stackables#9] opened 2016-07-08 16:28 UTC
One can see by going to `admin tools` - > credentials, then adjust the browser width to be narrow, then click the hovercard directive, you should see the popover is displayed behind the search input

**Comment by dlongley** [comment] 2017-03-08 17:24
Closing as fixed (as it seems to be). Reopen or file a new issue if it can be reproduced.

**Closed as completed** 2017-03-08 17:24 UTC
